### ISSUE TITLE
experimenting with kratos-keto-flask: docker-compose up is giving me `AttributeError: module 'jinja2.ext' has no attribute 'with_'`

### ISSUE THREAD

**Issue by arasic** [ory/examples#18]
inputs:
directory: `ory-examples/kratos-keto-flask`
command: `docker-compose up`

output trace:
```
kratos-selfservice-ui-node_1  | Listening on http://0.0.0.0:3000
kratos-keto-flask_flask_1 exited with code 1
flask_1                       |  * Serving Flask app 'autoapp.py' (lazy loading)
flask_1                       |  * Environment: development
flask_1                       |  * Debug mode: on
flask_1                       | Traceback (most recent call last):
flask_1                       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/bin/flask", line 8, in <module>
flask_1                       |     sys.exit(main())
flask_1                       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/flask/cli.py", line 994, in main
flask_1                       |     cli.main(args=sys.argv[1:])
flask_1                       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/flask/cli.py", line 600, in main
flask_1                       |     return super().main(*args, **kwargs)
flask_1                       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/click/core.py", line 1055, in main
flask_1                       |     rv = self.invoke(ctx)
flask_1                       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
flask_1                       |     return _process_result(sub_ctx.command.invoke(sub_ctx))
flask_1                       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
flask_1                       |     return ctx.invoke(self.callback, **ctx.params)
flask_1                       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/click/core.py", line 760, in invoke
flask_1                       |     return __callback(*args, **kwargs)
flask_1                       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/click/decorators.py", line 84, in new_func
flask_1                       |     return ctx.invoke(f, obj, *args, **kwargs)
flask_1                       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/click/core.py", line 760, in invoke
flask_1                       |     return __callback(*args, **kwargs)
flask_1                       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/flask/cli.py", line 849, in run_command
flask_1                       |     app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
flask_1                       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/flask/cli.py", line 324, in __init__
flask_1                       |     self._load_unlocked()
flask_1                       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/flask/cli.py", line 350, in _load_unlocked
flask_1                       |     self._app = rv = self.loader()
flask_1                       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/flask/cli.py", line 406, in load_app
flask_1                       |     app = locate_app(self, import_name, name)
flask_1                       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/flask/cli.py", line 260, in locate_app
flask_1                       |     __import__(module_name)
flask_1                       |   File "/app/autoapp.py", line 3, in <module>
flask_1                       |     from app.app import create_app
flask_1                       |   File "/app/app/app.py", line 9, in <module>
flask_1                       |     from app.extensions import db, debug_toolbar
flask_1                       |   File "/app/app/extensions.py", line 10, in <module>
flask_1                       |     debug_toolbar = DebugToolbarExtension()
flask_1                       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/flask_debugtoolbar/__init__.py", line 50, in __init__
flask_1                       |     self.jinja_env = Environment(
flask_1                       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/jinja2/environment.py", line 363, in __init__
flask_1                       |     self.extensions = load_extensions(self, extensions)
flask_1                       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/jinja2/environment.py", line 117, in load_extensions
flask_1                       |     extension = t.cast(t.Type["Extension"], import_string(extension))
flask_1                       |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/jinja2/utils.py", line 149, in import_string
flask_1                       |     return getattr(__import__(module, None, None, [obj]), obj)
flask_1                       | AttributeError: module 'jinja2.ext' has no attribute 'with_'
```

Solution:

Was able to reproduce it locally, `pipenv graph` was outputting:
```
- Jinja2 [required: >=3.0, installed: 3.1.2]
```

setting in `Pipenv` solves the issue:
```
jinja2 = "==3.0.2"
```

Just need to make sure to rebuild with `docker-compose build flask` and then `docker-compose up`
Its probably not the most elegant solution, but it worked :)

**Comment by vinckr** [comment]
Hello arasic,

thanks for reporting!

Can you take a look at this @gen1us2k 🙏
